---
apiVersion: v1
kind: LimitRange
metadata:
  name: admission-resources
spec:
  limits:
    - type: Container
      default:
        memory: 256Mi
      defaultRequest:
        memory: 64Mi
        cpu: 20m
      max:
        memory: 16Gi
    - type: Pod
      max:
        memory: 16Gi