# Only manually triggered for now
trigger: none
pr: none

# Define resources for container to use
resources:
  containers:
    - container: python-ce
      image: dfdsdk/python-ce:latest
      env:
        AWS_ROLE_CLOUD_ADMIN: $(AWS_ROLE_CLOUD_ADMIN)
        AWS_ROLE_ADFS_ADMIN: $(AWS_ROLE_ADFS_ADMIN)
        SAML2AWS_USERNAME: $(USERNAME)
        SAML2AWS_PASSWORD: $(PASSWORD)
        SAML2AWS_URL: $(SAML_URL)
        KUBECONFIG_URL: $(KUBECONFIG_URL)
stages:
  # Continuous Integration steps
  - stage: CI
    displayName: "Continuous Integration"
    pool:
      vmImage: "ubuntu-latest"

    jobs:
      - job: exec_script
        displayName: Execute Python script
        container: python-ce
        steps:
          - bash: |
              DOWNLOAD_URL=$KUBECONFIG_URL
              LOCAL_FILE=~/.kube/hellman-saml.config
              PARENT_DIR=$(dirname $LOCAL_FILE)
              mkdir -p $PARENT_DIR
              curl -Lo $LOCAL_FILE $DOWNLOAD_URL
              echo "##vso[task.setvariable variable=KUBECONFIG]$LOCAL_FILE"
              echo "##vso[task.setvariable variable=AWS_PROFILE]saml"
            displayName: Download Kube Config
          - bash: saml2aws configure --idp-provider ADFS --mfa Auto --skip-prompt
            displayName: Configure SAML2AWS
            env:
              SAML2AWS_PASSWORD: $(SAML2AWS_PASSWORD)
          - bash: poetry install
            workingDirectory: ./k8s-service-account-config-to-ssm/
            displayName: "Initialise Poetry"
          - bash: |
              env | sort
              poetry run python --version
              #poetry run python ./kube_config_generator.py -r $ROOTID -a $ACCOUNTID
            workingDirectory: ./k8s-service-account-config-to-ssm/
            displayName: "Execute kube_config_generator script"
            env:
              ROOTID: $(RootID)
              ACCOUNTID: $(AccountID)
