# Define resources for container to use
resources:
  containers:
    - container: python-ce
      image: dfdsdk/python-ce:latest
      env:
        AWS_ROLE_CLOUD_ADMIN: $(AWS_ROLE_CLOUD_ADMIN)
        AWS_ROLE_ADFS_ADMIN: $(AWS_ROLE_ADFS_ADMIN)

stages:
  # Continuous Integration steps
  - stage: CI
    displayName: "Continuous Integration"
    pool:
      vmImage: "ubuntu-latest"

    jobs:
      - job: exec_script
        displayName: Execute Python script
        container: python-ce
        steps:
          - bash: poetry install
            workingDirectory: ./k8s-service-account-config-to-ssm/
            displayName: "Initialise Poetry"
          - bash: poetry run python ./kube_config_generator.py --help
            workingDirectory: ./k8s-service-account-config-to-ssm/
            displayName: "Execute kube_config_generator script"
